#
# Vivado (TM) v2016.2 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'ethernet_core'
#
# Generated by Vivado on Wed Oct 12 16:10:40 CEST 2016
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/new/udp_rx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/new/udp_tx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/new/main.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/ip/gig_ethernet_core/gig_ethernet_core.xci"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/ip/ila_0/ila_0.xci"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/crc32_gen/new/crc32_gen_ooc.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sources_1/ip/ila_1/ila_1.xci"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/constrs_1/new/main.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sim_1/new/simul.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.srcs/sim_1/new/simul_behav.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]

variable script_file
set script_file "build.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ethernet_core $origin_dir/ethernet_core -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects ethernet_core]
set_property "board_part" "xilinx.com:kc705:part0:1.3" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/udp_rx.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/udp_tx.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/main.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ethernet_core.srcs/sources_1/new/udp_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/udp_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/main.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "main" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/ip/gig_ethernet_core/gig_ethernet_core.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/ip/ila_0/ila_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'crc32_gen' fileset (if not found)
if {[string equal [get_filesets -quiet crc32_gen] ""]} {
  create_fileset -blockset crc32_gen
}

# Set 'crc32_gen' fileset object
set obj [get_filesets crc32_gen]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/crc32_gen/new/crc32_gen_ooc.xdc"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'crc32_gen' fileset file properties for remote files
set file "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets crc32_gen] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/crc32_gen/new/crc32_gen_ooc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets crc32_gen] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "used_in" "synthesis implementation out_of_context" $file_obj


# Set 'crc32_gen' fileset file properties for local files
# None

# Set 'crc32_gen' fileset properties
set obj [get_filesets crc32_gen]
set_property "top" "crc32_gen" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/ip/ila_1/ila_1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/ethernet_core.srcs/constrs_1/new/main.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/ethernet_core.srcs/constrs_1/new/main.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "$orig_proj_dir/ethernet_core.srcs/constrs_1/new/main.xdc" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sim_1/new/simul.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sim_1/new/simul_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/ethernet_core.srcs/sim_1/new/simul.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "simul" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.view" "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.sim/simul_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj

# Create 'crc32_gen_synth_1' run (if not found)
if {[string equal [get_runs -quiet crc32_gen_synth_1] ""]} {
  create_run -name crc32_gen_synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset crc32_gen
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs crc32_gen_synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs crc32_gen_synth_1]
}
set obj [get_runs crc32_gen_synth_1]
set_property "constrset" "crc32_gen" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "needs_refresh" "1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# Create 'crc32_gen_impl_1' run (if not found)
if {[string equal [get_runs -quiet crc32_gen_impl_1] ""]} {
  create_run -name crc32_gen_impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset crc32_gen -parent_run crc32_gen_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs crc32_gen_impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs crc32_gen_impl_1]
}
set obj [get_runs crc32_gen_impl_1]
set_property "constrset" "crc32_gen" $obj
set_property "include_in_archive" "0" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:ethernet_core"
