#
# Vivado (TM) v2016.2 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'ethernet_core'
#
# Generated by Vivado on Fri Nov 25 16:18:57 CET 2016
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_bank_package.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_banks_user_setup.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_sync_pulse.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_sync_block.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_gt.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_cpll_railing.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_bank_package.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_tx_dpram/xlx_k7v7_tx_dpram.xci"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_tx_startup_fsm.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_tx_manual_phase_align.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_rx_startup_fsm.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_multi_gt.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_auto_phase_align.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_init.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_std.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_latopt.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.xci"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_phasemon.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_status.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/gbt_rx_frameclk_phalgnr/xlx_k7v7_phalgnr_std_mmcm.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/phaligner_phase_computing.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/phaligner_phase_comparator.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/gbt_rx_frameclk_phalgnr/phaligner_mmcm_controller.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/mgt/multi_gigabit_transceivers.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/gbt_rx_frameclk_phalgnr.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/gbt_bank_reset.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_bank.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_tx_pll/xlx_k7v7_tx_pll.xci"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/xlx_k7v7_reset.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/udp_tx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/udp_rx.vhd"
#    "/home/harankom/Projects/gbt_fpga_4_1_0/gbt_interface/gbt_interface.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/main.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/crc32_gen/new/crc32_gen_ooc.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/ip/gig_ethernet_core/gig_ethernet_core.xci"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/ip/ila_1/ila_1.xci"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/ip/ila_0/ila_0.xci"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/constrs_1/new/main.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/gbt_fpga_4_1_0/gbt_interface/constraints/kc705_exmpldsgn_floorplanning.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsgn_clks.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsgn_io.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsn_timingclosure.xdc"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sim_1/new/simul.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sim_1/new/simul_behav.wcfg"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sources_1/new/udp_tx.vhd"
#    "/home/harankom/Soft/Xilinx/Projects/fpga_ethernet/ethernet_core.srcs/sim_2/new/simul_tx.vhd"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "build.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/ethernet_core"]"

# Create project
create_project ethernet_core ./ethernet_core -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects ethernet_core]
set_property "board_part" "xilinx.com:kc705:part0:1.3" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_bank_package.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_banks_user_setup.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_sync_pulse.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_sync_block.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_gt.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_cpll_railing.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_bank_package.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_tx_dpram/xlx_k7v7_tx_dpram.xci"]"\
 "[file normalize "$origin_dir/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_tx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_tx_manual_phase_align.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_rx_startup_fsm.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_multi_gt.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_auto_phase_align.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_init.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_std.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_latopt.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.xci"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_phasemon.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_status.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_rx_frameclk_phalgnr/xlx_k7v7_phalgnr_std_mmcm.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/phaligner_phase_computing.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/phaligner_phase_comparator.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_rx_frameclk_phalgnr/phaligner_mmcm_controller.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/mgt/multi_gigabit_transceivers.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/gbt_rx_frameclk_phalgnr.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_bank_reset.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_bank.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core/ethernet_core.srcs/sources_1/ip/xlx_k7v7_tx_pll/xlx_k7v7_tx_pll.xci"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/xlx_k7v7_reset.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/udp_tx.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/udp_rx.vhd"]"\
 "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_interface.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/main.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_bank_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_banks_user_setup.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_sync_pulse.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_sync_block.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_gt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_cpll_railing.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_bank_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_tx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_tx_manual_phase_align.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_rx_startup_fsm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_multi_gt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_auto_phase_align.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip_init.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/mgt_ip_vhd/xlx_k7v7_mgt_ip.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/mgt/mgt_latopt_bitslipctrl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_std.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_latopt.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_phasemon.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_status.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_rx_frameclk_phalgnr/xlx_k7v7_phalgnr_std_mmcm.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/phaligner_phase_computing.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/phaligner_phase_comparator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_rx_frameclk_phalgnr/phaligner_mmcm_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/mgt/multi_gigabit_transceivers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_tx/gbt_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_rx/gbt_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/rxframeclk_phalgnr/gbt_rx_frameclk_phalgnr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_bank_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_bank/core_sources/gbt_bank.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/xlx_k7v7_reset.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/udp_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/udp_rx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/gbt_interface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/main.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "main" $obj

# Create 'crc32_gen' fileset (if not found)
if {[string equal [get_filesets -quiet crc32_gen] ""]} {
  create_fileset -blockset crc32_gen
}

# Set 'crc32_gen' fileset object
set obj [get_filesets crc32_gen]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/crc32_gen/new/crc32_gen_ooc.xdc"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'crc32_gen' fileset file properties for remote files
set file "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets crc32_gen] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/crc32_gen/new/crc32_gen_ooc.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets crc32_gen] [list "*$file"]]
set_property "file_type" "XDC" $file_obj
set_property "used_in" "synthesis implementation out_of_context" $file_obj


# Set 'crc32_gen' fileset file properties for local files
# None

# Set 'crc32_gen' fileset properties
set obj [get_filesets crc32_gen]
set_property "top" "crc32_gen" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/ip/gig_ethernet_core/gig_ethernet_core.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/ip/ila_1/ila_1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/ip/ila_0/ila_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/ethernet_core.srcs/constrs_1/new/main.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/ethernet_core.srcs/constrs_1/new/main.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_exmpldsgn_floorplanning.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_exmpldsgn_floorplanning.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsgn_clks.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsgn_clks.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsgn_io.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsgn_io.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsn_timingclosure.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../gbt_fpga_4_1_0/gbt_interface/constraints/kc705_gbt_exmpldsn_timingclosure.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/ethernet_core.srcs/constrs_1/new/main.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sim_1/new/simul.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sim_1/new/simul_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/ethernet_core.srcs/sim_1/new/simul.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "simul" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.view" "/home/harankom/Soft/Xilinx/Projects/ethernet_core/ethernet_core.sim/simul_behav.wcfg" $obj

# Create 'sim_2' fileset (if not found)
if {[string equal [get_filesets -quiet sim_2] ""]} {
  create_fileset -simset sim_2
}

# Set 'sim_2' fileset object
set obj [get_filesets sim_2]
set files [list \
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sources_1/new/udp_tx.vhd"]"\
 "[file normalize "$origin_dir/ethernet_core.srcs/sim_2/new/simul_tx.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_2' fileset file properties for remote files
set file "$origin_dir/ethernet_core.srcs/sources_1/new/crc32_gen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_2] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sources_1/new/udp_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_2] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/ethernet_core.srcs/sim_2/new/simul_tx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_2] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sim_2' fileset file properties for local files
# None

# Set 'sim_2' fileset properties
set obj [get_filesets sim_2]
set_property "source_set" "" $obj
set_property "top" "simul_tx" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]

# Create 'crc32_gen_synth_1' run (if not found)
if {[string equal [get_runs -quiet crc32_gen_synth_1] ""]} {
  create_run -name crc32_gen_synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset crc32_gen
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs crc32_gen_synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs crc32_gen_synth_1]
}
set obj [get_runs crc32_gen_synth_1]
set_property "constrset" "crc32_gen" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# Create 'crc32_gen_impl_1' run (if not found)
if {[string equal [get_runs -quiet crc32_gen_impl_1] ""]} {
  create_run -name crc32_gen_impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset crc32_gen -parent_run crc32_gen_synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs crc32_gen_impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs crc32_gen_impl_1]
}
set obj [get_runs crc32_gen_impl_1]
set_property "constrset" "crc32_gen" $obj
set_property "include_in_archive" "0" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:ethernet_core"
